BEGIN;

ALTER TABLE "Order" ALTER COLUMN "currentStatus" DROP DEFAULT;

ALTER TABLE "StatusHistory"
  ALTER COLUMN "toStatus" TYPE TEXT USING "toStatus"::text;

ALTER TABLE "StatusHistory"
  ALTER COLUMN "fromStatus" TYPE TEXT USING CASE
    WHEN "fromStatus" IS NULL THEN NULL
    ELSE "fromStatus"::text
  END;

ALTER TABLE "Order"
  ALTER COLUMN "currentStatus" TYPE TEXT USING "currentStatus"::text;

ALTER TYPE "OrderStatus" RENAME TO "OrderStatus_old";

CREATE TYPE "OrderStatus" AS ENUM (
  'FATURADO',
  'AGUARDANDO_CARREGAMENTO',
  'CARREGADO',
  'SAIU_PARA_ENTREGA',
  'ENTREGUE',
  'ENTREGA_PARCIAL',
  'CLIENTE_AUSENTE',
  'RECUSADO',
  'DEVOLUCAO',
  'OCORRENCIA'
);

UPDATE "Order"
SET "currentStatus" = CASE "currentStatus"
  WHEN 'IMPORTED' THEN 'FATURADO'
  WHEN 'AVAILABLE' THEN 'AGUARDANDO_CARREGAMENTO'
  WHEN 'ASSIGNED' THEN 'CARREGADO'
  WHEN 'ON_ROUTE' THEN 'SAIU_PARA_ENTREGA'
  WHEN 'DELIVERED' THEN 'ENTREGUE'
  WHEN 'FAILED' THEN 'OCORRENCIA'
  WHEN 'RETURNED' THEN 'DEVOLUCAO'
  ELSE 'OCORRENCIA'
END;

UPDATE "StatusHistory"
SET "toStatus" = CASE "toStatus"
  WHEN 'IMPORTED' THEN 'FATURADO'
  WHEN 'AVAILABLE' THEN 'AGUARDANDO_CARREGAMENTO'
  WHEN 'ASSIGNED' THEN 'CARREGADO'
  WHEN 'ON_ROUTE' THEN 'SAIU_PARA_ENTREGA'
  WHEN 'DELIVERED' THEN 'ENTREGUE'
  WHEN 'FAILED' THEN 'OCORRENCIA'
  WHEN 'RETURNED' THEN 'DEVOLUCAO'
  ELSE 'OCORRENCIA'
END;

UPDATE "StatusHistory"
SET "fromStatus" = CASE "fromStatus"
  WHEN 'IMPORTED' THEN 'FATURADO'
  WHEN 'AVAILABLE' THEN 'AGUARDANDO_CARREGAMENTO'
  WHEN 'ASSIGNED' THEN 'CARREGADO'
  WHEN 'ON_ROUTE' THEN 'SAIU_PARA_ENTREGA'
  WHEN 'DELIVERED' THEN 'ENTREGUE'
  WHEN 'FAILED' THEN 'OCORRENCIA'
  WHEN 'RETURNED' THEN 'DEVOLUCAO'
  ELSE 'OCORRENCIA'
END
WHERE "fromStatus" IS NOT NULL;

ALTER TABLE "Order"
  ALTER COLUMN "currentStatus" TYPE "OrderStatus" USING "currentStatus"::"OrderStatus";

ALTER TABLE "StatusHistory"
  ALTER COLUMN "toStatus" TYPE "OrderStatus" USING "toStatus"::"OrderStatus";

ALTER TABLE "StatusHistory"
  ALTER COLUMN "fromStatus" TYPE "OrderStatus" USING CASE
    WHEN "fromStatus" IS NULL THEN NULL
    ELSE "fromStatus"::"OrderStatus"
  END;

ALTER TABLE "Order"
  ALTER COLUMN "currentStatus" SET DEFAULT 'FATURADO';

DROP TYPE "OrderStatus_old";

COMMIT;
